// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1YvJQ2oFYT_qgcyF0jT2t_eZWDPQHqa8',
    appId: '1:342193248635:web:108a9f489686e6ae40c5de',
    messagingSenderId: '342193248635',
    projectId: 'slams-8588b',
    authDomain: 'slams-8588b.firebaseapp.com',
    storageBucket: 'slams-8588b.firebasestorage.app',
    measurementId: 'G-QYWNTTQ9BX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuNMUk1ewlegbJJkPzeCNRlvndsHyjVfc',
    appId: '1:342193248635:android:4c8494fda755ce7440c5de',
    messagingSenderId: '342193248635',
    projectId: 'slams-8588b',
    storageBucket: 'slams-8588b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB0LZLoTJeED_o9Suv4FaoQfEw3JrAjZU',
    appId: '1:342193248635:ios:678565b9b044981540c5de',
    messagingSenderId: '342193248635',
    projectId: 'slams-8588b',
    storageBucket: 'slams-8588b.firebasestorage.app',
    iosBundleId: 'com.example.slamstat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB0LZLoTJeED_o9Suv4FaoQfEw3JrAjZU',
    appId: '1:342193248635:ios:678565b9b044981540c5de',
    messagingSenderId: '342193248635',
    projectId: 'slams-8588b',
    storageBucket: 'slams-8588b.firebasestorage.app',
    iosBundleId: 'com.example.slamstat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1YvJQ2oFYT_qgcyF0jT2t_eZWDPQHqa8',
    appId: '1:342193248635:web:d1f2d46b401e4f6540c5de',
    messagingSenderId: '342193248635',
    projectId: 'slams-8588b',
    authDomain: 'slams-8588b.firebaseapp.com',
    storageBucket: 'slams-8588b.firebasestorage.app',
    measurementId: 'G-2K0HKEKRSB',
  );
}
